### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by mamorlis** [Nishihara-Daiki/lsj#3]
取りまとめありがとうございます。
このリソースそれぞれのライセンスは何になるのでしょうか？　
明示されていた方が使いやすいので、それぞれにつけていただけると助かります。

**Comment by Nishihara-Daiki** [comment]
コメントありがとうございます。確認して11月中旬までに対応します。

**Comment by Nishihara-Daiki** [comment]
すみませんが、体調崩して予定より遅れています。回復次第対応します。

**Comment by Nishihara-Daiki** [comment]
@mamorlis お待たせしました。#4 で対応しましたので、close します。
READMEの末尾にライセンスを追記しています。
